# -*- coding: utf-8 -*-
"""AluraStore-projeto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-uhqVNd1dv76fZ4jNHqk99Eg9ih1RkPO

### Importação dos dados
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_1.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_4.csv"

loja = pd.read_csv(url)
loja2 = pd.read_csv(url2)
loja3 = pd.read_csv(url3)
loja4 = pd.read_csv(url4)

loja.head()

"""#1. Análise do faturamento


"""

loja['Faturamento'] = loja['Preço'] + loja['Frete']
loja2['Faturamento'] = loja2['Preço'] + loja2['Frete']
loja3['Faturamento'] = loja3['Preço'] + loja3['Frete']
loja4['Faturamento'] = loja4['Preço'] + loja4['Frete']

f1 = loja['Faturamento'].sum()
f2 = loja2['Faturamento'].sum()
f3 = loja3['Faturamento'].sum()
f4 = loja4['Faturamento'].sum()

print("Loja 1:", round(f1, 2))
print("Loja 2:", round(f2, 2))
print("Loja 3:", round(f3, 2))
print("Loja 4:", round(f4, 2))

"""# 2. Vendas por Categoria"""

print("Loja 1 - Categorias:")
print(loja['Categoria do Produto'].value_counts())
print()

print("Loja 2 - Categorias:")
print(loja2['Categoria do Produto'].value_counts())
print()

print("Loja 3 - Categorias:")
print(loja3['Categoria do Produto'].value_counts())
print()

print("Loja 4 - Categorias:")
print(loja4['Categoria do Produto'].value_counts())



"""# 3. Média de Avaliação das Lojas

"""

media1 = round(loja['Avaliação da compra'].mean(), 2)
media2 = round(loja2['Avaliação da compra'].mean(), 2)
media3 = round(loja3['Avaliação da compra'].mean(), 2)
media4 = round(loja4['Avaliação da compra'].mean(), 2)

print("Loja 1:", media1)
print("Loja 2:", media2)
print("Loja 3:", media3)
print("Loja 4:", media4)



"""# 4. Produtos Mais e Menos Vendidos"""

print("Loja 1 - Mais vendido:")
print(loja['Produto'].value_counts().head(1))
print("Menos vendido:")
print(loja['Produto'].value_counts().tail(1))
print()

print("Loja 2 - Mais vendido:")
print(loja2['Produto'].value_counts().head(1))
print("Menos vendido:")
print(loja2['Produto'].value_counts().tail(1))
print()

print("Loja 3 - Mais vendido:")
print(loja3['Produto'].value_counts().head(1))
print("Menos vendido:")
print(loja3['Produto'].value_counts().tail(1))
print()

print("Loja 4 - Mais vendido:")
print(loja4['Produto'].value_counts().head(1))
print("Menos vendido:")
print(loja4['Produto'].value_counts().tail(1))

"""# 5. Frete Médio por Loja"""

frete1 = round(loja['Frete'].mean(), 2)
frete2 = round(loja2['Frete'].mean(), 2)
frete3 = round(loja3['Frete'].mean(), 2)
frete4 = round(loja4['Frete'].mean(), 2)

print("Loja 1:", frete1)
print("Loja 2:", frete2)
print("Loja 3:", frete3)
print("Loja 4:", frete4)

import matplotlib.pyplot as plt

lojas = ['Loja 1', 'Loja 2', 'Loja 3', 'Loja 4']
faturamentos = [f1, f2, f3, f4]

plt.figure(figsize=(8,5))
plt.bar(lojas, faturamentos)

plt.title('Faturamento Total por Loja')
plt.xlabel('Lojas')
plt.ylabel('Faturamento')
plt.xticks(rotation=0)

plt.show()

plt.figure(figsize=(8,5))
barras = plt.bar(lojas, faturamentos)

plt.title('Faturamento Total por Loja')
plt.xlabel('Lojas')
plt.ylabel('Faturamento')

for barra in barras:
    y = barra.get_height()
    plt.text(barra.get_x() + barra.get_width()/2, y, f'{y:,.0f}',
             ha='center', va='bottom')

plt.show()

avaliacoes = [media1, media2, media3, media4]

plt.figure(figsize=(8,5))
barras = plt.bar(lojas, avaliacoes)

plt.title('Média de Avaliação por Loja')
plt.xlabel('Lojas')
plt.ylabel('Avaliação Média')

for barra in barras:
    y = barra.get_height()
    plt.text(barra.get_x() + barra.get_width()/2, y, f'{y:.2f}',
             ha='center', va='bottom')

plt.ylim(3.9, 4.1)  # deixa mais visual a diferença
plt.show()

fretes = [frete1, frete2, frete3, frete4]

plt.figure(figsize=(8,5))
barras = plt.bar(lojas, fretes)

plt.title('Frete Médio por Loja')
plt.xlabel('Lojas')
plt.ylabel('Frete Médio')

for barra in barras:
    y = barra.get_height()
    plt.text(barra.get_x() + barra.get_width()/2, y, f'{y:.2f}',
             ha='center', va='bottom')

plt.show()



"""# Relatório de Análise — Alura Store

## 1. Faturamento

A Loja 1 apresentou o maior faturamento (R$ 1.616.347,09), seguida pela Loja 2 e Loja 3. A Loja 4 apresentou o menor faturamento entre as quatro unidades.

## 2. Categorias Mais Vendidas

Em todas as lojas, a categoria "móveis" foi a mais vendida, demonstrando um padrão de consumo semelhante entre as unidades.

## 3. Média de Avaliação

A Loja 3 apresentou a melhor média de avaliação (4.05), enquanto a Loja 1 apresentou a menor (3.98). Apesar de todas as lojas manterem avaliações próximas de 4, há diferença na satisfação dos clientes.

## 4. Produtos Mais e Menos Vendidos

Cada loja apresentou um produto de destaque, porém nenhuma apresentou variações extremas entre os produtos mais e menos vendidos.

## 5. Frete Médio

A Loja 1 apresentou o maior frete médio (34.69), enquanto a Loja 4 apresentou o menor (31.28).

## Conclusão

Embora a Loja 1 possua o maior faturamento, ela apresenta a menor avaliação média e o maior frete médio, indicando possível risco competitivo a longo prazo.

A Loja 4, por sua vez, apresenta o menor faturamento entre as quatro unidades, sem se destacar positivamente nas demais métricas analisadas.

Dessa forma, recomenda-se que o Senhor João considere a venda da **Loja 4**, por apresentar o menor desempenho financeiro geral.

"""